### ISSUE TITLE
El Capitan support

### ISSUE THREAD

**Issue by joelhandwell** [samrocketman/vagrant-mac#1]
Is there any plan to have El Capitan supported?

**Comment by samrocketman** [comment]
These boxes weren't created by me.  I'm merely referencing them for my own benefit and ease of "vagrant up".  I see you have already asked in the upstream repo. AndrewDryga/vagrant-box-osx#37

You can track progress there.  If I find an image that someone else has created I'll probably create a Vagrantfile for it like I did the other versions.
